package main

const listAccounts = "list-accounts"
const listMedia = "list-media"
const listMenus = "list-menus"
const listQueues = "list-queues"
const listRoutes = "list-routes"
const listSchedules = "list-schedules"
const listSms = "list-sms"
const listSubaccounts = "list-subaccounts"
const listApplications = "list-applications"
const listCallLogs = "list-call-logs"
const listDevices = "list-devices"
const listExpressServiceCodes = "list-express-service-codes"
const listExtensions = "list-extensions"
const listContacts = "list-contacts"
const listGroups = "list-groups"
const listPhoneNumbers = "list-phone-numbers"
const listTrunks = "list-trunks"
const listAvailablePhoneNumbers = "list-available-phone-numbers"
const listAvailablePhoneNumberRegions = "list-available-phone-number-regions"
const createQueue = "create-queue"
const deleteQueue = "delete-queue"
const replaceQueue = "replace-queue"
const getQueue = "get-queue"
const createTrunk = "create-trunk"
const getTrunk = "get-trunk"
const replaceTrunk = "replace-trunk"
const deleteTrunk = "delete-trunk"
const createRoute = "create-route"
const createSubaccount = "create-subaccount"
const deleteRoute = "delete-route"
const replaceRoute = "replace-route"
const createSms = "create-sms"
const createMenu = "create-menu"
const getMenu = "get-menu"
const getRecording = "get-recording"
const getRoute = "get-route"
const getSchedule = "get-schedule"
const getSms = "get-sms"
const getAccount = "get-account"
const getApplication = "get-application"
const getCallLog = "get-call-log"
const getDevice = "get-device"
const getExtension = "get-extension"
const getExpressServiceCode = "get-express-service-code"
const getCallerId = "get-caller-id"
const getContact = "get-contact"
const getGroup = "get-group"
const getPhoneNumber = "get-phone-number"
const replaceMenu = "replace-menu"
const deleteMenu = "delete-menu"
const createPhoneNumber = "create-phone-number"
const createCall = "create-call"
const createDevice = "create-device"
const createExtension = "create-extension"
const createContact = "create-contact"
const createGroup = "create-group"

const replaceDevice = "replace-device"
const replaceExtension = "replace-extension"
const replaceContact = "replace-contact"
const replaceGroup = "replace-group"
const replacePhoneNumber = "replace-phone-number"

const deleteContact = "delete-contact"
const deleteGroup = "delete-group"


const responseError = "@error"
const responseHttpStatusCode = "@httpStatusCode"
const responseMessage = "@message"

const msgCouldNotGetResponse = "Could not get response from API"
const msgInvalidJson = "Phone.com API Error: Invalid JSON"
const msgHttpError = "Phone.com API HTTP Error: %v %v"
const msgCallingApi = "Calling '%+v' with parameters: %+v, expecting JSON response\n"
