//
// AddressListContacts.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class AddressListContacts: JSONEncodable {
    /** Address type, one of: home or business. Default is home. */
    public var type: String?
    /** House number and street name, including apartment, suite, etc. */
    public var street: String?
    /** City */
    public var city: String?
    /** State or province */
    public var state: String?
    /** Zip code or postal code */
    public var zip: String?
    /** Country name */
    public var country: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["type"] = self.type
        nillableDictionary["street"] = self.street
        nillableDictionary["city"] = self.city
        nillableDictionary["state"] = self.state
        nillableDictionary["zip"] = self.zip
        nillableDictionary["country"] = self.country
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
