//
// RouteFull.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The root level of the Full Route Object includes all of the properties in the Route Summary Object, along with two more: */
open class RouteFull: JSONEncodable {
    /** Integer ID. Read-only. */
    public var id: Int32?
    /** Name */
    public var name: String?
    /** Extension to which this route belongs. Output is an Extension Summary Object. Input must be an Extension Lookup Object. Optional. Cannot be changed after a route is created. */
    public var _extension: ExtensionSummary?
    /** Array of Rule Set Objects. Required. See below for details. When processing incoming calls, the first matching rule set will be used, and all others will be ignored. */
    public var rules: [RuleSet]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["extension"] = self._extension?.encodeToJSON()
        nillableDictionary["rules"] = self.rules?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
