/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// The Full Phone Number Object has all of the properties of the Phone Number Summary Object, along with several more, as shown below:
    /// </summary>
    [DataContract]
    public partial class PhoneNumberFull :  IEquatable<PhoneNumberFull>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PhoneNumberFull" /> class.
        /// </summary>
        /// <param name="Id">Integer Phone number ID. This is the internal Phone.com ID for this number, not the phone number itself. Read-only..</param>
        /// <param name="Name">Name.</param>
        /// <param name="PhoneNumber">Phone number, in E.164 format.</param>
        /// <param name="BlockIncoming">Whether to block incoming calls. Boolean..</param>
        /// <param name="BlockAnonymous">Whether to block anonymous calls. Boolean..</param>
        /// <param name="Route">The Route assigned to handle incoming calls for this number, if any. Output is a Route Summary Object, or NULL if not set. Input can be a Route Lookup Object or NULL to unset..</param>
        /// <param name="CallerId">Caller ID Object, or NULL.</param>
        /// <param name="SmsForwarding">SMS Forwarding Object, or NULL.</param>
        /// <param name="CallNotifications">CallNotifications.</param>
        public PhoneNumberFull(int? Id = default(int?), string Name = default(string), string PhoneNumber = default(string), bool? BlockIncoming = default(bool?), bool? BlockAnonymous = default(bool?), RouteSummary Route = default(RouteSummary), CallerIdPhoneNumber CallerId = default(CallerIdPhoneNumber), SmsForwarding SmsForwarding = default(SmsForwarding), CallNotifications CallNotifications = default(CallNotifications))
        {
            this.Id = Id;
            this.Name = Name;
            this.PhoneNumber = PhoneNumber;
            this.BlockIncoming = BlockIncoming;
            this.BlockAnonymous = BlockAnonymous;
            this.Route = Route;
            this.CallerId = CallerId;
            this.SmsForwarding = SmsForwarding;
            this.CallNotifications = CallNotifications;
        }
        
        /// <summary>
        /// Integer Phone number ID. This is the internal Phone.com ID for this number, not the phone number itself. Read-only.
        /// </summary>
        /// <value>Integer Phone number ID. This is the internal Phone.com ID for this number, not the phone number itself. Read-only.</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }
        /// <summary>
        /// Name
        /// </summary>
        /// <value>Name</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }
        /// <summary>
        /// Phone number, in E.164 format
        /// </summary>
        /// <value>Phone number, in E.164 format</value>
        [DataMember(Name="phone_number", EmitDefaultValue=false)]
        public string PhoneNumber { get; set; }
        /// <summary>
        /// Whether to block incoming calls. Boolean.
        /// </summary>
        /// <value>Whether to block incoming calls. Boolean.</value>
        [DataMember(Name="block_incoming", EmitDefaultValue=false)]
        public bool? BlockIncoming { get; set; }
        /// <summary>
        /// Whether to block anonymous calls. Boolean.
        /// </summary>
        /// <value>Whether to block anonymous calls. Boolean.</value>
        [DataMember(Name="block_anonymous", EmitDefaultValue=false)]
        public bool? BlockAnonymous { get; set; }
        /// <summary>
        /// The Route assigned to handle incoming calls for this number, if any. Output is a Route Summary Object, or NULL if not set. Input can be a Route Lookup Object or NULL to unset.
        /// </summary>
        /// <value>The Route assigned to handle incoming calls for this number, if any. Output is a Route Summary Object, or NULL if not set. Input can be a Route Lookup Object or NULL to unset.</value>
        [DataMember(Name="route", EmitDefaultValue=false)]
        public RouteSummary Route { get; set; }
        /// <summary>
        /// Caller ID Object, or NULL
        /// </summary>
        /// <value>Caller ID Object, or NULL</value>
        [DataMember(Name="caller_id", EmitDefaultValue=false)]
        public CallerIdPhoneNumber CallerId { get; set; }
        /// <summary>
        /// SMS Forwarding Object, or NULL
        /// </summary>
        /// <value>SMS Forwarding Object, or NULL</value>
        [DataMember(Name="sms_forwarding", EmitDefaultValue=false)]
        public SmsForwarding SmsForwarding { get; set; }
        /// <summary>
        /// Gets or Sets CallNotifications
        /// </summary>
        [DataMember(Name="call_notifications", EmitDefaultValue=false)]
        public CallNotifications CallNotifications { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PhoneNumberFull {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  PhoneNumber: ").Append(PhoneNumber).Append("\n");
            sb.Append("  BlockIncoming: ").Append(BlockIncoming).Append("\n");
            sb.Append("  BlockAnonymous: ").Append(BlockAnonymous).Append("\n");
            sb.Append("  Route: ").Append(Route).Append("\n");
            sb.Append("  CallerId: ").Append(CallerId).Append("\n");
            sb.Append("  SmsForwarding: ").Append(SmsForwarding).Append("\n");
            sb.Append("  CallNotifications: ").Append(CallNotifications).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as PhoneNumberFull);
        }

        /// <summary>
        /// Returns true if PhoneNumberFull instances are equal
        /// </summary>
        /// <param name="other">Instance of PhoneNumberFull to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PhoneNumberFull other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Id == other.Id ||
                    this.Id != null &&
                    this.Id.Equals(other.Id)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.PhoneNumber == other.PhoneNumber ||
                    this.PhoneNumber != null &&
                    this.PhoneNumber.Equals(other.PhoneNumber)
                ) && 
                (
                    this.BlockIncoming == other.BlockIncoming ||
                    this.BlockIncoming != null &&
                    this.BlockIncoming.Equals(other.BlockIncoming)
                ) && 
                (
                    this.BlockAnonymous == other.BlockAnonymous ||
                    this.BlockAnonymous != null &&
                    this.BlockAnonymous.Equals(other.BlockAnonymous)
                ) && 
                (
                    this.Route == other.Route ||
                    this.Route != null &&
                    this.Route.Equals(other.Route)
                ) && 
                (
                    this.CallerId == other.CallerId ||
                    this.CallerId != null &&
                    this.CallerId.Equals(other.CallerId)
                ) && 
                (
                    this.SmsForwarding == other.SmsForwarding ||
                    this.SmsForwarding != null &&
                    this.SmsForwarding.Equals(other.SmsForwarding)
                ) && 
                (
                    this.CallNotifications == other.CallNotifications ||
                    this.CallNotifications != null &&
                    this.CallNotifications.Equals(other.CallNotifications)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Id != null)
                    hash = hash * 59 + this.Id.GetHashCode();
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.PhoneNumber != null)
                    hash = hash * 59 + this.PhoneNumber.GetHashCode();
                if (this.BlockIncoming != null)
                    hash = hash * 59 + this.BlockIncoming.GetHashCode();
                if (this.BlockAnonymous != null)
                    hash = hash * 59 + this.BlockAnonymous.GetHashCode();
                if (this.Route != null)
                    hash = hash * 59 + this.Route.GetHashCode();
                if (this.CallerId != null)
                    hash = hash * 59 + this.CallerId.GetHashCode();
                if (this.SmsForwarding != null)
                    hash = hash * 59 + this.SmsForwarding.GetHashCode();
                if (this.CallNotifications != null)
                    hash = hash * 59 + this.CallNotifications.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
