/*
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Address;

/**
 * ContactAccount
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-03-13T08:15:06.119Z")
public class ContactAccount {
  @SerializedName("name")
  private String name = null;

  @SerializedName("company")
  private String company = null;

  @SerializedName("address")
  private Address address = null;

  @SerializedName("phone")
  private String phone = null;

  @SerializedName("fax")
  private String fax = null;

  @SerializedName("primary_email")
  private String primaryEmail = null;

  @SerializedName("alternate_email")
  private String alternateEmail = null;

  public ContactAccount name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name. Required.
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Name. Required.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ContactAccount company(String company) {
    this.company = company;
    return this;
  }

   /**
   * Company name
   * @return company
  **/
  @ApiModelProperty(example = "null", value = "Company name")
  public String getCompany() {
    return company;
  }

  public void setCompany(String company) {
    this.company = company;
  }

  public ContactAccount address(Address address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @ApiModelProperty(example = "null", value = "")
  public Address getAddress() {
    return address;
  }

  public void setAddress(Address address) {
    this.address = address;
  }

  public ContactAccount phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Phone number. Required.
   * @return phone
  **/
  @ApiModelProperty(example = "null", value = "Phone number. Required.")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public ContactAccount fax(String fax) {
    this.fax = fax;
    return this;
  }

   /**
   * Fax number
   * @return fax
  **/
  @ApiModelProperty(example = "null", value = "Fax number")
  public String getFax() {
    return fax;
  }

  public void setFax(String fax) {
    this.fax = fax;
  }

  public ContactAccount primaryEmail(String primaryEmail) {
    this.primaryEmail = primaryEmail;
    return this;
  }

   /**
   * Primary email address. Required.
   * @return primaryEmail
  **/
  @ApiModelProperty(example = "null", value = "Primary email address. Required.")
  public String getPrimaryEmail() {
    return primaryEmail;
  }

  public void setPrimaryEmail(String primaryEmail) {
    this.primaryEmail = primaryEmail;
  }

  public ContactAccount alternateEmail(String alternateEmail) {
    this.alternateEmail = alternateEmail;
    return this;
  }

   /**
   * Alternate email address
   * @return alternateEmail
  **/
  @ApiModelProperty(example = "null", value = "Alternate email address")
  public String getAlternateEmail() {
    return alternateEmail;
  }

  public void setAlternateEmail(String alternateEmail) {
    this.alternateEmail = alternateEmail;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContactAccount contactAccount = (ContactAccount) o;
    return Objects.equals(this.name, contactAccount.name) &&
        Objects.equals(this.company, contactAccount.company) &&
        Objects.equals(this.address, contactAccount.address) &&
        Objects.equals(this.phone, contactAccount.phone) &&
        Objects.equals(this.fax, contactAccount.fax) &&
        Objects.equals(this.primaryEmail, contactAccount.primaryEmail) &&
        Objects.equals(this.alternateEmail, contactAccount.alternateEmail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, company, address, phone, fax, primaryEmail, alternateEmail);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContactAccount {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    fax: ").append(toIndentedString(fax)).append("\n");
    sb.append("    primaryEmail: ").append(toIndentedString(primaryEmail)).append("\n");
    sb.append("    alternateEmail: ").append(toIndentedString(alternateEmail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

