/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The Account Summary Object is used to briefly represent an account. It can occur in several places throughout this API. Here are the properties:
type AccountSummary struct {

	// Account ID. Sometimes referred to as \"Voip ID\" or \"voip_id\".
	Id int32 `json:"id,omitempty"`

	// Name on the account. Read-only.
	Name string `json:"name,omitempty"`
}
