/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The Full Available Phone Number Object includes the properties in the Summary Object, along with the following:
type AvailableNumbersFull struct {

	// Phone number, in E.164 format
	PhoneNumber string `json:"phone_number,omitempty"`

	// Human-readable formatted version of the phone number
	Formatted string `json:"formatted,omitempty"`

	// The one-time initial price for this number, in USD. Some numbers show REQUEST_QUOTE here. Please contact our sales department if you are interested in these numbers.
	Price int32 `json:"price,omitempty"`

	// Whether the number is toll-free
	IsTollFree bool `json:"is_toll_free,omitempty"`

	// The international dialing prefix for this number. For US and Canadian numbers, for example, this will be \"1\".
	CountryCode string `json:"country_code,omitempty"`

	// Area code (a.k.a. NPA). Included for North American numbers only.
	Npa string `json:"npa,omitempty"`

	// Second 3 digits (a.k.a. NXX). Included for North American numbers only.
	Nxx string `json:"nxx,omitempty"`

	// Last 4 digits (a.k.a. XXXX). Included for North American numbers only.
	Xxxx string `json:"xxxx,omitempty"`

	// City with which this number is associated, if known. Otherwise NULL.
	City string `json:"city,omitempty"`

	// State or Province with which this number is associated, if known. Postal Code. Otherwise NULL.
	Province string `json:"province,omitempty"`

	// Country with which this number is associated, if known. Otherwise NULL.
	Country string `json:"country,omitempty"`
}
