#import <Foundation/Foundation.h>
#import "SWGCreateMediaParams.h"
#import "SWGListMedia.h"
#import "SWGMediaFull.h"
#import "SWGApi.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGMediaApi: NSObject <SWGApi>

extern NSString* kSWGMediaApiErrorDomain;
extern NSInteger kSWGMediaApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Add a media object to your account that can be used as a greeting or hold music. Users may create a media by using the built-in Text-to-speech (TTS) facility or upload a file of their choice. (Note: The maximum size for media files or JSON objects included with a POST or PUT request is 10 MB)
/// See Account Media for more info on the properties.
///
/// @param accountId Account ID
/// @param data Media data (optional)
/// 
///  code:201 message:"Created",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:422 message:"Invalid Data"
///
/// @return SWGMediaFull*
-(NSURLSessionTask*) createAccountMediaWithAccountId: (NSNumber*) accountId
    data: (SWGCreateMediaParams*) data
    completionHandler: (void (^)(SWGMediaFull* output, NSError* error)) handler;


/// Show details of an individual media recording (Greeting or Hold Music)
/// Get individual media recording
///
/// @param accountId Account ID
/// @param recordingId Recording ID
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGMediaFull*
-(NSURLSessionTask*) getAccountMediaWithAccountId: (NSNumber*) accountId
    recordingId: (NSNumber*) recordingId
    completionHandler: (void (^)(SWGMediaFull* output, NSError* error)) handler;


/// Get a list of media recordings for an account
/// See Account Menus for more info on the properties.
///
/// @param accountId Account ID
/// @param filtersId ID filter (optional)
/// @param filtersName Name filter (optional)
/// @param sortId ID sorting (optional)
/// @param sortName Name sorting (optional)
/// @param limit Max results (optional)
/// @param offset Results to skip (optional)
/// @param fields Field set (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden"
///
/// @return SWGListMedia*
-(NSURLSessionTask*) listAccountMediaWithAccountId: (NSNumber*) accountId
    filtersId: (NSArray<NSString*>*) filtersId
    filtersName: (NSArray<NSString*>*) filtersName
    sortId: (NSString*) sortId
    sortName: (NSString*) sortName
    limit: (NSNumber*) limit
    offset: (NSNumber*) offset
    fields: (NSString*) fields
    completionHandler: (void (^)(SWGListMedia* output, NSError* error)) handler;



@end
