/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TrunksApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class TrunksApiTests
    {
        private TrunksApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TrunksApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TrunksApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' TrunksApi
            //Assert.IsInstanceOfType(typeof(TrunksApi), instance, "instance is a TrunksApi");
        }

        
        /// <summary>
        /// Test CreateAccountTrunk
        /// </summary>
        [Test]
        public void CreateAccountTrunkTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? accountId = null;
            //CreateTrunkParams data = null;
            //var response = instance.CreateAccountTrunk(accountId, data);
            //Assert.IsInstanceOf<TrunkFull> (response, "response is TrunkFull");
        }
        
        /// <summary>
        /// Test DeleteAccountTrunk
        /// </summary>
        [Test]
        public void DeleteAccountTrunkTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? accountId = null;
            //int? trunkId = null;
            //var response = instance.DeleteAccountTrunk(accountId, trunkId);
            //Assert.IsInstanceOf<DeleteTrunk> (response, "response is DeleteTrunk");
        }
        
        /// <summary>
        /// Test GetAccountTrunk
        /// </summary>
        [Test]
        public void GetAccountTrunkTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? accountId = null;
            //int? trunkId = null;
            //var response = instance.GetAccountTrunk(accountId, trunkId);
            //Assert.IsInstanceOf<TrunkFull> (response, "response is TrunkFull");
        }
        
        /// <summary>
        /// Test ListAccountTrunks
        /// </summary>
        [Test]
        public void ListAccountTrunksTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? accountId = null;
            //List<string> filtersId = null;
            //List<string> filtersName = null;
            //string sortId = null;
            //string sortName = null;
            //int? limit = null;
            //int? offset = null;
            //string fields = null;
            //var response = instance.ListAccountTrunks(accountId, filtersId, filtersName, sortId, sortName, limit, offset, fields);
            //Assert.IsInstanceOf<ListTrunks> (response, "response is ListTrunks");
        }
        
        /// <summary>
        /// Test ReplaceAccountTrunk
        /// </summary>
        [Test]
        public void ReplaceAccountTrunkTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? accountId = null;
            //int? trunkId = null;
            //CreateTrunkParams data = null;
            //var response = instance.ReplaceAccountTrunk(accountId, trunkId, data);
            //Assert.IsInstanceOf<TrunkFull> (response, "response is TrunkFull");
        }
        
    }

}
