# coding: utf-8

"""
    Phone.com API

    This is a Phone.com api Swagger definition

    OpenAPI spec version: 1.0.0
    Contact: apisupport@phone.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.hold_music import HoldMusic


class TestHoldMusic(unittest.TestCase):
    """ HoldMusic unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHoldMusic(self):
        """
        Test HoldMusic
        """
        model = swagger_client.models.hold_music.HoldMusic()


if __name__ == '__main__':
    unittest.main()
