# coding: utf-8

"""
    Phone.com API

    This is a Phone.com api Swagger definition

    OpenAPI spec version: 1.0.0
    Contact: apisupport@phone.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.media_api import MediaApi


class TestMediaApi(unittest.TestCase):
    """ MediaApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.media_api.MediaApi()

    def tearDown(self):
        pass

    def test_create_account_media(self):
        """
        Test case for create_account_media

        Add a media object to your account that can be used as a greeting or hold music. Users may create a media by using the built-in Text-to-speech (TTS) facility or upload a file of their choice. (Note: The maximum size for media files or JSON objects included with a POST or PUT request is 10 MB)
        """
        pass

    def test_get_account_media(self):
        """
        Test case for get_account_media

        Show details of an individual media recording (Greeting or Hold Music)
        """
        pass

    def test_list_account_media(self):
        """
        Test case for list_account_media

        Get a list of media recordings for an account
        """
        pass


if __name__ == '__main__':
    unittest.main()
