# coding: utf-8

"""
    Phone.com API

    This is a Phone.com api Swagger definition

    OpenAPI spec version: 1.0.0
    Contact: apisupport@phone.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.create_call_params import CreateCallParams


class TestCreateCallParams(unittest.TestCase):
    """ CreateCallParams unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateCallParams(self):
        """
        Test CreateCallParams
        """
        model = swagger_client.models.create_call_params.CreateCallParams()


if __name__ == '__main__':
    unittest.main()
