/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.ContactSummary;
import io.swagger.client.model.GroupSummary;
import io.swagger.client.model.ScheduleSummary;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Filter Object. Optional. See below for details.
 **/
@ApiModel(description = "Filter Object. Optional. See below for details.")
public class RuleSetFilter {
  
  @SerializedName("type")
  private String type = null;
  @SerializedName("schedule")
  private ScheduleSummary schedule = null;
  @SerializedName("contact")
  private ContactSummary contact = null;
  @SerializedName("group")
  private GroupSummary group = null;

  /**
   * Required.
   **/
  @ApiModelProperty(value = "Required.")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }

  /**
   * Schedule that this filter refers to. Output is a Schedule Summary Object. Input must be a Schedule Lookup Object. Required.
   **/
  @ApiModelProperty(value = "Schedule that this filter refers to. Output is a Schedule Summary Object. Input must be a Schedule Lookup Object. Required.")
  public ScheduleSummary getSchedule() {
    return schedule;
  }
  public void setSchedule(ScheduleSummary schedule) {
    this.schedule = schedule;
  }

  /**
   * Address Book Contact that this filter refers to. Output is a Contact Summary Object. Input must be a Contact Lookup Object. Required.
   **/
  @ApiModelProperty(value = "Address Book Contact that this filter refers to. Output is a Contact Summary Object. Input must be a Contact Lookup Object. Required.")
  public ContactSummary getContact() {
    return contact;
  }
  public void setContact(ContactSummary contact) {
    this.contact = contact;
  }

  /**
   * Address Book Group that this filter refers to. Output is a Contact Group Summary Object. Input must be a Contact Group Lookup Object. Required.
   **/
  @ApiModelProperty(value = "Address Book Group that this filter refers to. Output is a Contact Group Summary Object. Input must be a Contact Group Lookup Object. Required.")
  public GroupSummary getGroup() {
    return group;
  }
  public void setGroup(GroupSummary group) {
    this.group = group;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RuleSetFilter ruleSetFilter = (RuleSetFilter) o;
    return (this.type == null ? ruleSetFilter.type == null : this.type.equals(ruleSetFilter.type)) &&
        (this.schedule == null ? ruleSetFilter.schedule == null : this.schedule.equals(ruleSetFilter.schedule)) &&
        (this.contact == null ? ruleSetFilter.contact == null : this.contact.equals(ruleSetFilter.contact)) &&
        (this.group == null ? ruleSetFilter.group == null : this.group.equals(ruleSetFilter.group));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.schedule == null ? 0: this.schedule.hashCode());
    result = 31 * result + (this.contact == null ? 0: this.contact.hashCode());
    result = 31 * result + (this.group == null ? 0: this.group.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RuleSetFilter {\n");
    
    sb.append("  type: ").append(type).append("\n");
    sb.append("  schedule: ").append(schedule).append("\n");
    sb.append("  contact: ").append(contact).append("\n");
    sb.append("  group: ").append(group).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
