/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import static org.junit.Assert.assertNotNull;

import java.util.List;

import org.junit.Before;
import org.junit.Test;

import io.swagger.client.ApiException;
import io.swagger.client.helper.TestConfig;
import io.swagger.client.model.CreateQueueParams;
import io.swagger.client.model.ListQueuesFull;
import io.swagger.client.model.QueueFull;

/**
 * API tests for QueuesApi
 */
public class QueuesApiTest {

    private final QueuesApi api = new QueuesApi();

    @Before
    public void initTest() {
    	TestConfig.setAuthorization();
    }
    
    /**
     * Create a queue
     *
     * For more on the input fields, see Account Queues.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAccountQueueTest() throws ApiException {
        Integer accountId = 1315091;
        CreateQueueParams data = null;
        data = new CreateQueueParams();
        data.setCallerIdType("caller");
        data.setMaxHoldTime(13);
        data.setName("TEST");
        data.setRingTime(10);
        
        // QueueFull response = api.createAccountQueue(accountId, data);
        
        // TODO: test validations
    }
    
    /**
     * Delete a queue
     *
     * This service a queue from the account. For more information on queue properties, see Account Queues.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteAccountQueueTest() throws ApiException {
        Integer accountId = null;
        Integer queueId = null;
        // DeleteQueue response = api.deleteAccountQueue(accountId, queueId);

        // TODO: test validations
    }
    
    /**
     * Show details of an individual queue
     *
     * This service shows the details of an individual queue. For more on the input fields, see Account Queues.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountQueueTest() throws ApiException {
        Integer accountId = 1315091;
        Integer queueId = null;
        // QueueFull response = api.getAccountQueue(accountId, queueId);

        // TODO: test validations
    }
    
    /**
     * Get a list of queues for an account
     *
     * The List Queues service lists all the queues belong to the account. See Account Queues for more info on the properties.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAccountQueuesTest() throws ApiException {
        Integer accountId = 1315091;
        List<String> filtersId = null;
        List<String> filtersName = null;
        String sortId = null;
        String sortName = null;
        Integer limit = null;
        Integer offset = null;
        String fields = null;
         ListQueuesFull response = api.listAccountQueues(accountId, filtersId, filtersName, sortId, sortName, limit, offset, fields);
         assertNotNull(response.getFilters());
         assertNotNull(response.getItems());
         assertNotNull(response.getLimit());
         assertNotNull(response.getOffset());
         assertNotNull(response.getSort());
         assertNotNull(response.getTotal());
        // TODO: test validations
    }
    
    /**
     * Replace a queue
     *
     * The Replace Queue service replaces the parameters of a queue. For more on the input fields, see Account Queues.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceAccountQueueTest() throws ApiException {
        Integer accountId = null;
        Integer queueId = null;
        CreateQueueParams data = null;
        // QueueFull response = api.replaceAccountQueue(accountId, queueId, data);

        // TODO: test validations
    }
    
}
