/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CallNotifications
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CallNotificationsTests
    {
        // TODO uncomment below to declare an instance variable for CallNotifications
        //private CallNotifications instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CallNotifications
            //instance = new CallNotifications();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CallNotifications
        /// </summary>
        [Test]
        public void CallNotificationsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CallNotifications
            //Assert.IsInstanceOfType<CallNotifications> (instance, "variable 'instance' is a CallNotifications");
        }

        /// <summary>
        /// Test the property 'Emails'
        /// </summary>
        [Test]
        public void EmailsTest()
        {
            // TODO unit test for the property 'Emails'
        }
        /// <summary>
        /// Test the property 'Sms'
        /// </summary>
        [Test]
        public void SmsTest()
        {
            // TODO unit test for the property 'Sms'
        }

    }

}
