/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PhoneNumbersRegionFull
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PhoneNumbersRegionFullTests
    {
        // TODO uncomment below to declare an instance variable for PhoneNumbersRegionFull
        //private PhoneNumbersRegionFull instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PhoneNumbersRegionFull
            //instance = new PhoneNumbersRegionFull();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PhoneNumbersRegionFull
        /// </summary>
        [Test]
        public void PhoneNumbersRegionFullInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PhoneNumbersRegionFull
            //Assert.IsInstanceOfType<PhoneNumbersRegionFull> (instance, "variable 'instance' is a PhoneNumbersRegionFull");
        }

        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Test]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }
        /// <summary>
        /// Test the property 'Npa'
        /// </summary>
        [Test]
        public void NpaTest()
        {
            // TODO unit test for the property 'Npa'
        }
        /// <summary>
        /// Test the property 'Nxx'
        /// </summary>
        [Test]
        public void NxxTest()
        {
            // TODO unit test for the property 'Nxx'
        }
        /// <summary>
        /// Test the property 'IsTollFree'
        /// </summary>
        [Test]
        public void IsTollFreeTest()
        {
            // TODO unit test for the property 'IsTollFree'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'ProvincePostalCode'
        /// </summary>
        [Test]
        public void ProvincePostalCodeTest()
        {
            // TODO unit test for the property 'ProvincePostalCode'
        }
        /// <summary>
        /// Test the property 'CountryPostalCode'
        /// </summary>
        [Test]
        public void CountryPostalCodeTest()
        {
            // TODO unit test for the property 'CountryPostalCode'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

    }

}
