/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SortListPhoneNumbersRegions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SortListPhoneNumbersRegionsTests
    {
        // TODO uncomment below to declare an instance variable for SortListPhoneNumbersRegions
        //private SortListPhoneNumbersRegions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SortListPhoneNumbersRegions
            //instance = new SortListPhoneNumbersRegions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SortListPhoneNumbersRegions
        /// </summary>
        [Test]
        public void SortListPhoneNumbersRegionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SortListPhoneNumbersRegions
            //Assert.IsInstanceOfType<SortListPhoneNumbersRegions> (instance, "variable 'instance' is a SortListPhoneNumbersRegions");
        }

        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Test]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }
        /// <summary>
        /// Test the property 'Npa'
        /// </summary>
        [Test]
        public void NpaTest()
        {
            // TODO unit test for the property 'Npa'
        }
        /// <summary>
        /// Test the property 'Nxx'
        /// </summary>
        [Test]
        public void NxxTest()
        {
            // TODO unit test for the property 'Nxx'
        }
        /// <summary>
        /// Test the property 'IsTollFree'
        /// </summary>
        [Test]
        public void IsTollFreeTest()
        {
            // TODO unit test for the property 'IsTollFree'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'ProvincePostalCode'
        /// </summary>
        [Test]
        public void ProvincePostalCodeTest()
        {
            // TODO unit test for the property 'ProvincePostalCode'
        }
        /// <summary>
        /// Test the property 'CountryPostalCode'
        /// </summary>
        [Test]
        public void CountryPostalCodeTest()
        {
            // TODO unit test for the property 'CountryPostalCode'
        }

    }

}
