#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGMediaSummary.h"


@protocol SWGTrunkFull
@end

@interface SWGTrunkFull : SWGObject

/* Integer Trunk ID. Read-only. 
 */
@property(nonatomic) NSNumber* _id;
/* Name. Required. 
 */
@property(nonatomic) NSString* name;
/* Fully-qualified SIP URI. Required. 
 */
@property(nonatomic) NSString* uri;
/* Max concurrent calls. Default is 10. 
 */
@property(nonatomic) NSNumber* maxConcurrentCalls;
/* Max minutes per month. Default is 750. 
 */
@property(nonatomic) NSNumber* maxMinutesPerMonth;
/* Greeting. Output is a Media Summary Object. Input must be a Media Lookup Object. Must refer to a media recording that has is_hold_music set to FALSE. 
 */
@property(nonatomic) SWGMediaSummary* greeting;
/* Error Message. Output is a Media Summary Object. Input must be a Media Lookup Object. Must refer to a media recording that has is_hold_music set to FALSE. 
 */
@property(nonatomic) SWGMediaSummary* errorMessage;
/* Custom audio codec configuration, if any is needed. If provided, must be a simple array containing the prioritized list of desired codecs. Supported codecs are: g711u 64k, g711u 56k, g711a 64k, g711a 56k, g7231, g728, g729, g729A, g729B, g729AB, gms full, rfc2833, t38, ilbc, h263, g722, g722_1, g729D, g729E, amr, amr_wb, efr, evrc, h264, mpeg4, red, cng, SIP Info to 2833 
 */
@property(nonatomic) NSArray<NSString*>* codecs;

@end
